config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: :destroy

  delete '/items/:id/photo/:photo_id', to: 'items#destroy_photo'

  get 'dashboard', to: 'dashboard#profile', as: :dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :price, numericality: { only_integer: true }
  belongs_to :user
  has_one :booking, dependent: :destroy
  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: {
      title: 'A',
      description: 'B'
   },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^dashboard$)/
  end

   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit({ roles: [] }, :email, :password, :password_confirmation, :first_name, :photo)
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @item = Item.find(params['item_id'])
    has_booking = !@item.booking.nil?
    @booking = Booking.new(item: @item, user: current_user)
    authorize @booking
    if !has_booking
      if @booking.save
          redirect_to request.referrer
        return
      end
    end
    render 'items/show', notice: 'Could not book'
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    authorize @booking

    redirect_to item_path(@booking.item)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def profile
    @user = current_user
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :destroy_photo]
  def index
    if params[:query].present?
      @items = policy_scope(Item.search_by_title_and_description(params[:query]))
    else
      @items = policy_scope(Item.geocoded).order(created_at: :desc)
    end
    @markers = @items.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude,
        image_url: helpers.asset_url('trashcanz.png')

      }
    end
  end

  def show
    seller = @item.user
    @first_three_items = seller.items.reject{|item| item == @item}.take(3)
    @first_photo = @item.photos.first
    @remaining_photos = @item.photos.reject{|photo| photo == @first_photo}
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    authorize @item
    if @item.save
      redirect_to item_path(@item), notice: 'item was successfully added.'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item), notice: 'item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: "item was successfully deleted"
  end

  def destroy_photo
    photo = @item.photos.find(params['photo_id'])
    photo.purge unless photo.nil?
    redirect_to edit_item_path(@item)
  end

  private

  def set_item
    @item = Item.find(params[:id])
    authorize @item
  end

  def item_params
    params.require(:item).permit(:title, :description, :price, :address, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/profile.html.erb
<h1 id="dashboard-title">My Dashboard</h1>
<div class="dashboard-container">
  <div class="user-info">
    <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, class: "profile-avatar" %>
    <% else %>
      <%= image_tag "https://i.ya-webdesign.com/images/default-avatar-png-18.png", class: "profile-avatar" %>
    <% end %>
    <div class="welcome-message">
      <h4>Welcome</h4>
      <h1><%= current_user.first_name %></h1>
    </div>

    <div class="profile-stat">
      <div class="counts">
        <%= @user.bookings.count %>
        <p>Bookings</p>
      </div>
      <div class="counts">
        <%= @user.items.count %>
        <p>Items</p>
      </div>
      <div class="counts">
        <% booked_items = [] %>
        <% @user.items.each do |item| %>
          <% booked_items << item if item.booking %>
        <% end %>
        <% earnings = 0 %>
        <% booked_items.each do |item| %>
          <% earnings += item.price %>
        <% end %>
        <%= "$#{earnings}" %>
        <p>Earnings</p>
      </div>
    </div>
  </div>

  <div class="user-items">
    <h2>My Bookings</h2>
    <div class="nav-cards">
      <% @user.bookings.each do |booking| %>
          <div class="nav-card" style= "background-image:url(
            <% if booking.item.photos.attached? %>
              <%= cl_image_path booking.item.photos.first.key, height: 300, width: 400, crop: :fill %>
            <% else %>
            <%= 'https://cdn4.iconfinder.com/data/icons/documents-letters-and-stationery/400/doc-14-512.png' %>
          <% end %>)">
          <%= link_to "", item_path(booking.item), class:"absolute-0-0" %>
          <h3><%= booking.item.title.capitalize %></h3>
          </div>
      <% end %>
    </div>


    <h2>My Items</h2>
    <div class="nav-cards">
      <% @user.items.each do |item| %>
          <div class="nav-card" style= "background-image:url(
            <% if item.photos.attached? %>
              <%= cl_image_path item.photos.first.key, height: 300, width: 400, crop: :fill %>
            <% else %>
              <%= 'https://cdn4.iconfinder.com/data/icons/documents-letters-and-stationery/400/doc-14-512.png' %>
            <% end %>)">
            <%= link_to "", item_path(item), class:"absolute-0-0" %>
            <h3><%= item.title.capitalize %></h3>
          </div>

      <% end %>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<div class="container">
  <h2 class="mt-3 text-center color">Edit Item</h2>
<%= simple_form_for [@item] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :address %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.button :submit, class: 'button' %>
    <% end %>

    <% @item.photos.each do |photo| %>
   <%=  cl_image_tag(photo.key, height: 300, width: 400, crop: :fill) %>
   <%= link_to 'delete photo',"/items/#{@item.id}/photo/#{photo.id}" , method: :delete, class: 'button' %>
    <% end %>
<%= link_to "back to item", item_path(@item), class: 'button' %>
</div>

app/views/items/index.html.erb
<div class="d-flex full-screen-container-index">
  <div class="left-container">
    <h1 class="text-center">All Used Items</h1>
    <%= form_tag items_path, method: :get, class: "search-bar" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control mr-2",
        placeholder: "Find a used item"
      %>
      <%= submit_tag "Search", class: "search-button m-0" %>
    <% end %>
      <!-- <div class="cards-container"> -->
        <div class="cards">
          <% @items.each do |item| %>
            <div class="item-card">
              <div class="item-card-img" style= "background-image:url(
                <% if item.photos.attached? %>
                  <%= cl_image_path item.photos.first.key, height: 300, width: 400, crop: :fill %>
                <% else %>
                  <%= 'https://cdn4.iconfinder.com/data/icons/documents-letters-and-stationery/400/doc-14-512.png' %>
                <% end %>)">
              </div>
                <div class="item-card-title">
                  <strong><%= item.title.capitalize %></strong>
                </div>
                <div class="item-date">
                  <p>Posted on: <strong><%= item.created_at.strftime("%b %d, %Y") %></strong></p>
                </div>
                <div class="item-card-info">
                  <%= link_to 'See Details', item_path(item), class: 'button' %>
                  <% if item.booking %>
                    <p class="item-reserved"> <strong><u>Reserved</u></strong></p>
                  <% else %>
                    <% if item.user == current_user %>
                      <p class="item-reserved"> <strong><u>My item</u></strong></p>
                    <% else %>
                      <%= link_to "I want it!", item_bookings_path(item), method: :post, class: 'button'  %>
                    <% end %>
                  <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <!-- </div> -->
    </div>
  <div class="right-container">
    <div
      id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
</div>

app/views/items/new.html.erb
<div class="form-container">
  <div class="form-flexbox">
  <!-- <h2 class="form font">Adding new <strong> Item</strong></h2> -->
  <div class="img">
  <img src="https://www.pawprintbadges.co.uk/ekmps/shops/9507f2/images/recycling-collection-255-p.png" alt="" class="img-center">
  </div>
  <div class="simple-form">
    <h2 class="new-form-title color">Add New Item</h2>
  <%= simple_form_for [@item] do |f| %>
        <%= f.input :title   %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :address %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.button :submit, class: 'button' %>
  <% end %>
  </div>
 </div>
 </div>

app/views/items/show.html.erb
<div class="show-container">
  <div class="show-page-card">
    <% if @first_photo %>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= cl_image_tag @first_photo.key, height: 400, width: 400, crop: :fill, class: 'd-block w-100 show-card-img' %>
          </div>
          <% @remaining_photos.each do |photo| %>
            <div class="carousel-item">
             <%= cl_image_tag photo.key, height: 400, width: 400, crop: :fill, class: 'd-block w-100 show-card-img' %>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    <% end %>
    <div class="show-card-details">
      <div class= "show-card-info">
        <h1 class= "show-card-title"><%= @item.title.capitalize %></h1>
        <p><strong>Price: </strong>$<%= @item.price %></p>
        <p><strong>About this item: </strong><%= @item.description %></p>
        <p><strong>Address: </strong><%= @item.address %></p>
      </div>
      <div class="show-card-links">
        <% if policy(@item).edit? %>
          <%= link_to edit_item_path(@item) do %>
          <p class='button'>Edit <i class="far fa-edit"></i></p>
          <% end %>
        <% end %>
        <% if policy(@item).destroy? %>
          <%= link_to  item_path(@item), method: :delete, data: { confirm: "Are you sure you want to delete this item?" } do %>
            <p class='ml-2 button'>Delete <i class="far fa-trash-alt"></i></p>
          <% end %>
        <% end %>

        <% if @item.booking %>
          <% if @item.booking.user == current_user %>
            <%= link_to "Cancel booking", booking_path(@item.booking), method: :delete, data: { confirm: "Are you sure you want to delete this booking?" }, class: 'button' %>
          <% end %>
        <% else %>
          <% if @item.user != current_user %>
            <%= link_to item_bookings_path(@item), method: :post do%>
              <p class='button'>Book <i class="far fa-bookmark"></i></p>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="show-card-booking">
      <% if @item.booking && @item.user == current_user %>
        <h3>Wow!</h3>
        <p><%= @item.booking.user.first_name %> has reserved your product.</p>
        <p class="no-margin">To arrange the transaction, please </p>
        <p>contact the buyer at:</p>
        <p class="email"><%= @item.booking.user.email %></p>
      <% elsif @item.user == current_user %>
        <h3>Welcome back!</h3>
        <p>This is your item.</p>
      <% elsif @item.booking.nil? %>
        <h3>Hello!</h3>
        <p>I'm looking for a new owner.</p>
      <% elsif @item.booking.user == current_user %>
        <h3>Yay!</h3>
        <p>You have reserved this item.</p>
        <p class="no-margin">To arrange the transaction, please</p>
        <p>contact the seller at:</p>
        <p class="email"><%= @item.user.email %></p>
      <% elsif @item.booking %>
        <h3>Sorry!</h3>
        <p>This item is reserved.</p>
      <% end %>
    </div>
  </div>
  <div class="other-items-by-seller">
    <h2>Other items by this seller</h2>
    <div class="item-seller-cards">
    <% @first_three_items.each do |item| %>
      <div class="item-by-seller-card">
        <% if item.photos.attached? %>
          <%= image_tag cl_image_path item.photos.first.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <%= image_tag 'https://cdn4.iconfinder.com/data/icons/documents-letters-and-stationery/400/doc-14-512.png' %>
        <% end %>
      <div class="item-seller-card-info">
        <h2><%= link_to "" , item_path(item), class: 'absolute-0-0' %></h2>
        <h2><%= item.title %></h2>
      </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Waste-list</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path('https://www.pawprintbadges.co.uk/ekmps/shops/9507f2/images/recycling-collection-255-p.png') %>
  </head>
  <body>
    <div id="page-container">
      <%= render 'shared/navbar' %>
      <div id="content-wrap">
      <%= yield %>
      <%= javascript_include_tag 'application' %>

      <%= javascript_pack_tag 'application' %>
      </div>
      <%#= render 'shared/footer' %>
      <%= render 'shared/flashes' %>
    </div>
   <!--  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1572950588591-00baf1832071?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <h1>Be wasteless with Waste-List</h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
    <a class="start-now-btn" href="/items">Start Now</a>
  </div>
</div>

<div class="container explain">
  <h2>How does it work?</h2>
  <div class="explain-section">
    <div class="explain-card">
      <img src="https://images.unsplash.com/photo-1519520104014-df63821cb6f9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="">
      <h3>Explore products</h3>
      <p>Search through all the products from our users, and find what you are looking for.</p>
    </div>

    <div class="explain-card">
      <img src="https://images.unsplash.com/photo-1533229613598-751dc97ec35f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="">
      <h3>Reserve the product</h3>
      <p>Reserve the product you like, contact the seller and arrange for item collection.</p>
    </div>

    <div class="explain-card">
      <img src="https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="">
      <h3>Enjoy your purchase</h3>
      <p>Receive your items, enjoy your purchase! And keep the Earth happy ♻️</p>
    </div>
  </div>
</div>

<div class="container user-stories">
  <h2>User Stories</h2>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="story-card">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(1).jpg" alt="" class="story-avatar">
          <div class="story-text">
            <p>I cannot believe how much I would enjoy Waste-List!! I managed to sell a lot of items that I thought that has no value, but you can always find the right person for the right item.</p>
            <p class="story-location">Alison, Tel Aviv</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="story-card">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTbnlWrY52t05hUEW43OG3DQEefPBYFCA7XjbEQNTbvn4bwJ52w" alt="" class="story-avatar">
          <div class="story-text">
            <p>I cannot believe how much I would enjoy Waste-List!! I managed to sell a lot of items that I thought that has no value, but you can always find the right person for the right item.</p>
            <p class="story-location">Emily, London</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="story-card">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSO0qEOI8T6sDmz9og_6pdaHe003itF0pHkbAvVa-ngfI7ub6rV" alt="" class="story-avatar">
          <div class="story-text">
            <p>I cannot believe how much I would enjoy Waste-List!! I managed to sell a lot of items that I thought that has no value, but you can always find the right person for the right item.</p>
            <p class="story-location">Daniel, Berlin</p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" id="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    With <i class="fas fa-heart"></i> at Waste-List
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <div class="navbar-logo">
      <div class="logo">
        <%= image_tag "https://www.pawprintbadges.co.uk/ekmps/shops/9507f2/images/recycling-collection-255-p.png" %>
      </div>
      <p class="logo-text">Waste-List</p>
    </div>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active mr-2">
          <div class="nav-text">
          <%= link_to items_path, class: "nav-link" do %>
            <i class="fas fa-list-ul"></i><i class="fas fa-recycle"></i>
            <p>All Waste</p>
          <% end %>
          </div>
        </li>
        <li class="nav-item active mr-2">
          <div class="nav-text">
          <%= link_to new_item_path, class: "nav-link" do %>
            <i class="fas fa-plus"></i><i class="fas fa-recycle"></i>
            <p>Add Waste</p>
          <% end %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://i.ya-webdesign.com/images/default-avatar-png-18.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>